<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { api, openEventSocket } from '../api/client'
type Migration={id:string;name:string;status:string;progress:number;speed_bytes_sec:number;speed_rows_sec?:number;eta_seconds?:number;sla_p95_eta_seconds?:number;sla_p99_eta_seconds?:number;sla_risk_level?:string;cdc_lag_ms:number;effective_parallelism?:number;parallelism?:number;flow_control_level?:string;cdc_spool_growth_bytes_sec?:number;cdc_spool_critical_eta_seconds?:number}
const tasks=ref<Migration[]>([]);let socket:WebSocket|undefined,timer:number|undefined
async function load(){tasks.value=await api('/api/v1/migrations')}
function connect(){try{socket=openEventSocket();socket.onmessage=(ev)=>{try{const m=JSON.parse(ev.data);const row=tasks.value.find(x=>x.id===m.task_id);if(!row)return;if(m.type==='task.progress')Object.assign(row,m);if(m.type==='cdc.metrics')row.cdc_lag_ms=m.lag_ms||0}catch{}}}catch{}}
onMounted(async()=>{await load();connect();timer=window.setInterval(load,15000)});onUnmounted(()=>{if(timer)clearInterval(timer);socket?.close()})
const mb=(v:number=0)=>(v/1024/1024).toFixed(1)
</script>
<template><div><div class="page-title"><div><h1>监控中心</h1><p>WebSocket 实时迁移吞吐、CDC Lag、动态并发与流控状态</p></div><el-button @click="load">刷新</el-button></div><div class="panel"><el-table :data="tasks"><el-table-column prop="name" label="任务" min-width="220"/><el-table-column prop="status" label="状态" width="180"/><el-table-column label="进度" width="160"><template #default="s"><el-progress :percentage="Math.round(s.row.progress||0)"/></template></el-table-column><el-table-column label="吞吐" width="120"><template #default="s">{{mb(s.row.speed_bytes_sec)}} MB/s</template></el-table-column><el-table-column label="Rows/s" width="110"><template #default="s">{{s.row.speed_rows_sec||0}}</template></el-table-column><el-table-column label="ETA" width="110"><template #default="s">{{s.row.eta_seconds||0}} s</template></el-table-column><el-table-column label="P99 ETA" width="110"><template #default="s">{{s.row.sla_p99_eta_seconds||0}} s</template></el-table-column><el-table-column label="SLA风险" width="110"><template #default="s"><el-tag :type="s.row.sla_risk_level==='CRITICAL'?'danger':s.row.sla_risk_level==='WARN'?'warning':'success'">{{s.row.sla_risk_level||'NONE'}}</el-tag></template></el-table-column><el-table-column label="CDC Lag" width="120"><template #default="s">{{s.row.cdc_lag_ms||0}} ms</template></el-table-column><el-table-column label="并发" width="110"><template #default="s">{{s.row.effective_parallelism||s.row.parallelism||0}} / {{s.row.parallelism||0}}</template></el-table-column><el-table-column label="流控" width="120"><template #default="s"><el-tag :type="s.row.flow_control_level==='CRITICAL'?'danger':s.row.flow_control_level==='WARN'?'warning':'success'">{{s.row.flow_control_level||'NORMAL'}}</el-tag></template></el-table-column><el-table-column label="Spool增长" width="120"><template #default="s">{{mb(s.row.cdc_spool_growth_bytes_sec||0)}} MB/s</template></el-table-column><el-table-column label="Spool临界ETA" width="130"><template #default="s">{{s.row.cdc_spool_critical_eta_seconds?`${s.row.cdc_spool_critical_eta_seconds}s`:'-'}}</template></el-table-column></el-table></div></div></template>
