<script setup lang="ts">
import {onMounted,onUnmounted,ref} from 'vue'
import {api,openEventSocket} from '../api/client'
const items=ref<any[]>([])
let timer:number|undefined, socket:WebSocket|undefined
async function load(){items.value=await api('/api/v1/workers')}
onMounted(()=>{load();timer=window.setInterval(load,15000);try{socket=openEventSocket();socket.onmessage=(ev)=>{try{const m=JSON.parse(ev.data);if(m.type==='worker.metrics'&&Array.isArray(m.workers))items.value=m.workers}catch{}}}catch{}})
onUnmounted(()=>{if(timer)clearInterval(timer);socket?.close()})
</script>
<template><div><div class="page-title"><div><h1>Worker 节点</h1><p>执行节点、心跳、拓扑标签、引擎能力与 WebSocket 实时指标</p></div><el-button @click="load">刷新</el-button></div><div class="panel"><el-table :data="items"><el-table-column prop="hostname" label="主机"/><el-table-column prop="status" label="状态"><template #default="s"><el-tag :type="s.row.status==='ONLINE'?'success':'warning'">{{s.row.status}}</el-tag></template></el-table-column><el-table-column prop="cpu" label="CPU核" width="80"/><el-table-column label="CPU使用" width="110"><template #default="s">{{(s.row.cpu_usage_pct||0).toFixed(1)}}%</template></el-table-column><el-table-column label="内存使用" width="110"><template #default="s">{{(s.row.memory_usage_pct||0).toFixed(1)}}%</template></el-table-column><el-table-column label="网络 RX/TX" min-width="170"><template #default="s">{{((s.row.network_rx_bps||0)/1024/1024).toFixed(1)}} / {{((s.row.network_tx_bps||0)/1024/1024).toFixed(1)}} MB/s</template></el-table-column><el-table-column prop="running_jobs" label="任务数" width="90"/><el-table-column label="调度负载" width="105"><template #default="s">{{(s.row.scheduler_load_score||0).toFixed(1)}}</template></el-table-column><el-table-column label="拓扑标签" min-width="220"><template #default="s"><el-tag v-for="(v,k) in (s.row.labels||{})" :key="k" type="info" style="margin-right:6px">{{k}}={{v}}</el-tag><span v-if="!Object.keys(s.row.labels||{}).length" class="muted">-</span></template></el-table-column><el-table-column label="能力" min-width="300"><template #default="s"><el-tag v-for="c in s.row.capabilities" :key="c" style="margin-right:6px">{{c}}</el-tag></template></el-table-column><el-table-column prop="last_heartbeat" label="最后心跳" min-width="220"/></el-table></div></div></template>
